name: my_project
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  http: ^0.14.0
  http_parser: ^4.0.0
  path_provider: ^2.0.11
  connectivity_plus: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
